# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven


on:
  push:
    branches: [ "test_FLINK-33607" ]
  pull_request:
    branches: [ "test_FLINK-33607" ]

jobs:
  buildOnLinux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: "./mvnw clean package -DskipTests"
  buildOnWindows:

    runs-on: windows-latest

    steps:
    - name: Allow long path
      run: git config --system core.longpaths true
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: "./mvnw clean package -DskipTests -Drat.skip=true"
  buildOnMacOs:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./mvnw clean package -DskipTests

  
    
